// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AbySalto.Junior.Models;

public class Currency
{
    public int CurrencyId { get; set; }
    public string CurrencyName { get; set; } = string.Empty;

    public ICollection<ItemPrice> ItemPrices { get; set; } = new List<ItemPrice>();
    public ICollection<Order> Orders { get; set; } = new List<Order>();
}
