// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AbySalto.Junior.Models;

public class ItemPrice
{
    public int ItemPriceId { get; set; }
    public int ItemId { get; set; }
    public decimal Price { get; set; }
    public int CurrencyId { get; set; }

    public Item Item { get; set; } = null!;
    public Currency Currency { get; set; } = null!;
    public ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}
