// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AbySalto.Junior.Models;

public class Item
{
    public int ItemId { get; set; }
    public string ItemName { get; set; } = string.Empty;

    public ICollection<ItemPrice> ItemPrices { get; set; } = new List<ItemPrice>();
}
