// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AbySalto.Junior.Models;
public class Order
{
    public int OrderId { get; set; }
    public int OrderStatusId { get; set; }
    public int PaymentTypeId { get; set; }
    public int CustomerAddressId { get; set; }
    public decimal? TotalValue { get; set; }
    public int CurrencyId { get; set; }
    public string? Comments { get; set; }
    public DateTime CreatedAt { get; set; }

    public Currency Currency { get; set; } = null!;
    public CustomerAddress CustomerAddress { get; set; } = null!;
    public OrderStatus OrderStatus { get; set; } = null!;
    public PaymentType PaymentType { get; set; } = null!;

    public ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}
